[build]
  base = "frontend"
  command = "npm run build"
  publish = "dist"

[build.environment]
  SECRETS_SCAN_ENABLED = "false"

# SPA 重定向规则 - 将所有路径重定向到 index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 或者更精确地忽略特定变量
# [build.environment]
#   SECRETS_SCAN_OMIT_KEYS = "VITE_FIREBASE_API_KEY,VITE_FIREBASE_APP_ID,VITE_FIREBASE_AUTH_DOMAIN,VITE_FIREBASE_PROJECT_ID,VITE_FIREBASE_STORAGE_BUCKET,VITE_FIREBASE_MESSAGING_SENDER_ID,VITE_FIREBASE_MEASUREMENT_ID,VITE_API_BASE_URL"