import * as functions from 'firebase-functions';
export declare const createUser: functions.HttpsFunction;
export declare const getUser: functions.HttpsFunction;
export declare const getMeetings: functions.HttpsFunction;
export declare const createMeeting: functions.HttpsFunction;
export declare const getMeeting: functions.HttpsFunction;
export declare const updateMeeting: functions.HttpsFunction;
export declare const deleteMeeting: functions.HttpsFunction;
export declare const createPreMeeting: functions.HttpsFunction;
export declare const getPreMeeting: functions.HttpsFunction;
export declare const updateObjective: functions.HttpsFunction;
export declare const addQuestion: functions.HttpsFunction;
export declare const createInMeeting: functions.HttpsFunction;
export declare const getInMeeting: functions.HttpsFunction;
export declare const addNote: functions.HttpsFunction;
export declare const createPostMeeting: functions.HttpsFunction;
export declare const getPostMeeting: functions.HttpsFunction;
export declare const updateSummary: functions.HttpsFunction;
export declare const addFeedback: functions.HttpsFunction;
export declare const onMeetingStatusChange: functions.CloudFunction<functions.Change<functions.firestore.QueryDocumentSnapshot>>;
export declare const onMeetingCreated: functions.CloudFunction<functions.firestore.QueryDocumentSnapshot>;
//# sourceMappingURL=old%20legacy%20code(to%20delete).d.ts.map